{
 "title": "New dashboard",
 "time": { "from": "2023-08-23T21:00:00.000Z", "to": "2024-08-22T21:00:00.000Z" },
 "panels": [
  {
   "title": "Динамика роста пользователей",
   "type": "timeseries",
   "description": "Изменение количества пользователей с течением времени",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, user_count\r\nFROM game_stats.user_growth\r\nORDER BY date\r\n"
    }
   ]
  },
  {
   "title": "Тренд прироста и оттока пользователей",
   "type": "status-history",
   "description": "График показывает количество новых и потерянных пользователей за последний месяц.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfWeek(login_times[1]) AS week, \r\n    COUNT(user_id) AS new_users\r\nFROM \r\n    game_stats.user_activity\r\nGROUP BY \r\n    week\r\nORDER BY \r\n    week ASC;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    toStartOfWeek(arrayElement(login_times, -1)) AS week, \r\n    COUNT(user_id) AS lost_users\r\nFROM \r\n    game_stats.user_activity\r\nWHERE \r\n    arrayElement(login_times, -1) < now() - INTERVAL 1 WEEK\r\nGROUP BY \r\n    week\r\nORDER BY \r\n    week ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Топ ошибок и сбоев",
   "type": "gauge",
   "description": "Наиболее частые типы ошибок и сбоев",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT error_type, COUNT(*) AS error_count\r\nFROM game_stats.error_logs\r\nGROUP BY error_type\r\nORDER BY error_count DESC\r\nLIMIT 5\r\n"
    }
   ]
  },
  {
   "title": "Финансовые транзакции",
   "type": "barchart",
   "description": "Общее количество и объем транзакций",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT transaction_type, COUNT(*) AS count, SUM(amount) AS total_amount\r\nFROM game_stats.financial_transactions\r\nGROUP BY transaction_type"
    }
   ]
  },
  {
   "title": "Среднее время в игре",
   "type": "gauge",
   "description": "Показывает среднее время, проведенное в игре пользователями",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_time\r\nFROM game_stats.avg_play_time\r\nORDER BY avg_time DESC\r\n"
    }
   ]
  },
  {
   "title": "Тепловая карта активности",
   "type": "heatmap",
   "description": "Активность пользователей в течение дня",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT hour, SUM(activity_score) AS activity\r\nFROM game_stats.activity_heatmap\r\nGROUP BY hour\r\nORDER BY hour\r\n"
    }
   ]
  },
  {
   "title": "Распределение побед и поражений",
   "type": "piechart",
   "description": "Сравнение общего количества побед и поражений",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(wins) AS total_wins, SUM(losses) AS total_losses\r\nFROM game_stats.win_loss_stats\r\n"
    }
   ]
  },
  {
   "title": "Топ активных пользователей",
   "type": "barchart",
   "description": "Пользователи с наибольшей активностью ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT user_id, SUM(activity_score) AS total_activity\r\nFROM game_stats.user_activity\r\nGROUP BY user_id\r\nORDER BY total_activity DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Частота игровых событий",
   "type": "bargauge",
   "description": "Распределение частоты различных типов игровых событий",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT event_type, COUNT(*) AS event_count\r\nFROM game_stats.game_events\r\nGROUP BY event_type\r\n"
    }
   ]
  }
 ]
}